services:
  bot:
    build: .
    container_name: alias-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Всё храним в одной папке data для чистоты
      - ./data:/app/data
    environment:
      - DICT_PATH=/app/data/dictionaries/
      - USER_DATA_FILE=/app/data/user_data.json
      - PYTHONUNBUFFERED=1
